version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: saneagest-postgres
    environment:
      POSTGRES_DB: saneagest
      POSTGRES_USER: sanea
      POSTGRES_PASSWORD: sanea123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
